### ISSUE TITLE
Problems compiling Project K kernel

### ISSUE THREAD

**Issue by POMATu** [khusika/projectk_kernel_xiaomi_msm8953#2]
Hi,

I am having problems compiling your kernel
https://github.com/khusika/projectk_kernel_xiaomi_msm8953/

I followed your instructions here
https://github.com/khusika/build-tools-clang

Everything compiles successfully. But that kernel just don't work, I get bootloop. While your compiled kernel works perfectly without any issue.

I am using latest release. The problem may be cause clang 7.x is much newer now than r344434. Is it possible to receive zip file from you with toolchain that you used and also any other environment options that you use?

My compilation script:

```
#!/bin/bash

rm -rf projectk_kernel_xiaomi_msm8953-r24
tar xf r24.tar.gz
cd projectk_kernel_xiaomi_msm8953-r24
make O=out ARCH=arm64 SUBARCH=arm64 tissot_defconfig
PATH="/home/user/kernel/try2/cmake-3.4.3/build-tools-clang/toolchains/clang-7.x/bin:/home/user/kernel/try2/arm-linux-androideabi-4.9/bin:/home/user/kernel/try2/aarch64-linux-android-4.9/bin:${PATH}" make -j$(nproc --all) O=out ARCH=arm64 SUBARCH=arm64 CC=clang CROSS_COMPILE=aarch64-linux-android- CLANG_TRIPLE=aarch64-linux-gnu- CROSS_COMPILE_ARM32=arm-linux-androideabi-
```

OS: Ubuntu 18.04 x86_64

I appreciate any kind of help,
Thanks

**Comment by khusika** [comment]
This project has been deprecated.
